MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: True
  SHAPEPROP_ON: False
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.0
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 9
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    CLASS_AGNOSTIC: True
SOLVER:
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 10000
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (21600, 28800,)
  MAX_ITER: 31500
  WARMUP_FACTOR: 0.03
  WARMUP_ITERS: 2000
INPUT:
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TRAIN: (360,)
TEST:
  IMS_PER_BATCH: 1
DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TRAIN: "(\"bdd100k_train\",)"
  TEST: "(\"bdd100k_val\",)"
DTYPE: float16
OUTPUT_DIR: "runs/bdd100k_mask_rcnn_r50_fpn_1x"